# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
