# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0002_auto_20160606_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
