# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 03:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0016_auto_20160607_0308'),
        ('docusign', '0003_auto_20160607_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('signed', 'Signed')], default=b'Sent', max_length=100)),
                ('envelope_id', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docusign.Document')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('email_subject', models.CharField(max_length=100, null=True)),
                ('email_blurb', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='DocumentTemplateRole',
            new_name='TemplateRole',
        ),
        migrations.DeleteModel(
            name='DocumentTemplate',
        ),
        migrations.AlterField(
            model_name='templaterole',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docusign.Template'),
        ),
        migrations.AddField(
            model_name='documentsigner',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docusign.TemplateRole'),
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docusign.Template'),
        ),
    ]
