# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import docusign.models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0005_documentattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='file',
            field=models.FileField(upload_to=docusign.models.upload_to),
        ),
    ]
