# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0006_auto_20160609_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templaterole',
            name='role_name',
            field=models.CharField(max_length=30),
        ),
    ]
