# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0007_auto_20160609_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRoleTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('template_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docusign.TemplateRole')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
