# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0009_documentsignertab'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsigner',
            name='status',
            field=models.CharField(choices=[(b'authenticationfailed', b'AuthenticationFailed'), (b'autoresponded', b'AutoResponded'), (b'signed', b'Signed'), (b'completed', b'Completed'), (b'declined', b'Declined'), (b'delivered', b'Delivered'), (b'sent', b'Sent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[(b'created', b'Created'), (b'sent', b'Sent'), (b'delivered', b'Delivered'), (b'completed', b'Completed'), (b'declined', b'Declined'), (b'voided', b'Voided')], default=b'Sent', max_length=100),
        ),
    ]
