# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0011_auto_20160616_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateroletab',
            name='type',
            field=models.CharField(choices=[(b'approveTabs', b'approveTabs'), (b'checkboxTabs', b'checkboxTabs'), (b'companyTabs', b'companyTabs'), (b'fullNameTabs', b'fullNameTabs'), (b'dateSignedTabs', b'dateSignedTabs'), (b'dateTabs', b'dateTabs'), (b'declineTabs', b'declineTabs'), (b'emailTabs', b'emailTabs'), (b'emailAddressTabs', b'emailAddressTabs'), (b'envelopeIdTabs', b'envelopeIdTabs'), (b'firstNameTabs', b'firstNameTabs'), (b'formulaTabs', b'formulaTabs'), (b'initialHereTabs', b'initialHereTabs'), (b'lastNameTabs', b'lastNameTabs'), (b'listTabs', b'listTabs'), (b'noteTabs', b'noteTabs'), (b'numberTabs', b'numberTabs'), (b'radioGroupTabs', b'radioGroupTabs'), (b'signHereTabs', b'signHereTabs'), (b'signerAttachmentTabs', b'signerAttachmentTabs'), (b'ssnTabs', b'ssnTabs'), (b'zipTabs', b'zipTabs')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templateroletab',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
