# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0012_auto_20160720_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateroletab',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
