# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0014_auto_20160720_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[(b'valid', b'still exists in docusign'), (b'deleted', b'was removed from docusign')], default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templaterole',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
