# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0015_auto_20160720_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[(b'created', b'Created'), (b'sent', b'Sent'), (b'delivered', b'Delivered'), (b'completed', b'Completed'), (b'declined', b'Declined'), (b'voided', b'Voided')], default=b'sent', max_length=100),
        ),
    ]
