# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0016_auto_20160810_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsignertab',
            name='value',
            field=models.TextField(),
        ),
    ]
