# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docusign', '0017_auto_20160818_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsignertab',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
