# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
