# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import generics.models
import generics.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0002_auto_20160719_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=generics.models.upload_to, validators=[generics.validators.file_validator]),
        ),
    ]
