# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0002_attachment_tag'),
        ('generics', '0003_auto_20160719_1127'),
    ]

    operations = [
    ]
