# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
