# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import generics.models
import generics.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0005_auto_20160802_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=generics.models.upload_to, validators=[generics.validators.file_validator]),
        ),
    ]
