# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0007_auto_20160818_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='upload_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 29, 18, 33, 48, 18182)),
            preserve_default=False,
        ),
    ]
