# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import generics.models
import generics.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0008_attachment_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=generics.models.upload_to, validators=[generics.validators.file_validator]),
        ),
    ]
