# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-12 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expertratings', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtest',
            name='skilltest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertratings.SkillTest'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='expertratings_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertratings.SkillTest'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', to='accounts.Skills'),
        ),
        migrations.AddField(
            model_name='skills',
            name='verification_tests',
            field=models.ManyToManyField(through='accounts.VerificationTest', to='expertratings.SkillTest'),
        ),
        migrations.AddField(
            model_name='connection',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='accounts.Role'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', blank=True, help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', to='accounts.Skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='skilltest',
            unique_together=set([('profile', 'expertratings_test')]),
        ),
        migrations.AlterUniqueTogether(
            name='skills',
            unique_together=set([('slug',)]),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('from_profile', 'to_profile')]),
        ),
    ]
