# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models
from accounts.enums import ROLES


def populate_display_names(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    for role in Role.objects.all():
        role.display_name = ROLES[role.category][role.name]
        role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171012_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(default='Full-Stack Developer', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(populate_display_names),
    ]
