# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160329_1230'),
        ('accounts', '0002_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='_Tagulous_Developer_skills',
        ),
        migrations.DeleteModel(
            name='_Tagulous_Profile_skills',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='ProjectManager',
        ),
    ]
