# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2),
        ),
    ]
