# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
