# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 08:51
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160505_0504'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
