# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models
from notifications.models import Notification


def remove_legacy_notifications(apps, schema_editor):
    for notification in Notification.objects.filter(data__isnull=False):
        if notification.data['type'] in ['connectionRequest', 'messageLimitReceived', 'connectionAccepted']:
            notification.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_referral_code'),
    ]

    operations = [
        migrations.RunPython(remove_legacy_notifications),
    ]
