# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expertratings', '0003_skilltestresult_skilltestuserfeedback'),
        ('accounts', '0009_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_url', models.CharField(blank=True, max_length=255, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expertrating_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertratings.SkillTest')),
                ('skills', tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', to='accounts.Skills')),
            ],
        ),
    ]
