# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_skilltest'),
        ('accounts', '0011_auto_20160714_1152'),
    ]

    operations = [
    ]
