# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilltest',
            old_name='developer',
            new_name='profile',
        ),
    ]
