# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160714_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilltest',
            old_name='expertrating_test',
            new_name='expertratings_test',
        ),
        migrations.AlterUniqueTogether(
            name='skilltest',
            unique_together=set([('profile', 'expertratings_test')]),
        ),
    ]
