# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 08:59
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160724_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', blank=True, help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', to='accounts.Skills'),
        ),
    ]
