# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20160815_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
