# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expertratings', '0005_auto_20160714_1855'),
        ('accounts', '0019_auto_20160816_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='verification_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expertratings.SkillTest'),
        ),
    ]
