# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-23 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expertratings', '0006_auto_20160831_1236'),
        ('accounts', '0020_skills_verification_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField()),
            ],
            options={
                'ordering': ('-relevance',),
            },
        ),
        migrations.RemoveField(
            model_name='skills',
            name='verification_test',
        ),
        migrations.AddField(
            model_name='verificationtest',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Skills'),
        ),
        migrations.AddField(
            model_name='verificationtest',
            name='skilltest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertratings.SkillTest'),
        ),
        migrations.AddField(
            model_name='skills',
            name='verification_tests',
            field=models.ManyToManyField(through='accounts.VerificationTest', to='expertratings.SkillTest'),
        ),
    ]
