# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-05 19:19
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20160923_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.path_and_rename),
        ),
    ]
