# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20161005_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
