# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-02 00:27
from __future__ import unicode_literals

from django.db import migrations

def move_phone(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    ContactDetails = apps.get_model('accounts', 'ContactDetails')
    for profile in Profile.objects.exclude(phone=u'').exclude(phone=None):
        try: 
            details = ContactDetails.objects.get(profile=profile)
            details.phone = profile.phone
            details.save()
        except ContactDetails.DoesNotExist:
            ContactDetails.objects.create(profile=profile, email=profile.email, phone=profile.phone)

def reverse_phone(apps, schema_editor):
    " for reversing the migration "
    Profile = apps.get_model('accounts', 'Profile')
    ContactDetails = apps.get_model('accounts', 'ContactDetails')
    for details in ContactDetails.objects.exclude(phone=u'').exclude(phone=None):
        details.profile.phone = details.phone
        details.profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_contactdetails'),
    ]

    operations = [
        migrations.RunPython(move_phone, reverse_code=reverse_phone),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
