# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-02 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_move_phone_to_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_profile', to=settings.AUTH_USER_MODEL)),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='connections',
            field=models.ManyToManyField(related_name='_profile_connections_+', through='accounts.Connection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('from_profile', 'to_profile')]),
        ),
    ]
