# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-16 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20161202_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
