# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20161216_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
