# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_profile_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
