# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-01 18:00
from __future__ import unicode_literals

from django.db import migrations, models

def convert_role(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Role = apps.get_model('accounts', 'Role')
    for profile in Profile.objects.all():
        if profile.role:
            role, created = Role.objects.get_or_create(name=profile.role)
            profile.roles.add(role)
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_profile_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('years', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='accounts.Role'),
        ),
        migrations.RunPython(convert_role),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),

    ]
