# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20170601_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_connect',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
