# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-15 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_role_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='field',
            new_name='category',
        ),
    ]
