# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-11 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_last_4',
            field=models.CharField(default='4242', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='card_type',
            field=models.CharField(default='Visa', max_length=20),
            preserve_default=False,
        ),
    ]
