# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-14 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170911_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
