# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-26 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_product_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('expire_date', models.DateField()),
                ('cents_off', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('percent_off', models.IntegerField(blank=True, null=True)),
                ('single_use', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('customers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Promo'),
        ),
    ]
