# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-27 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170926_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_charged',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
