# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-12 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='visitor')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sent at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='replied at')),
                ('sender_bookmarked', models.BooleanField(default=False, verbose_name='bookmarked by sender')),
                ('recipient_bookmarked', models.BooleanField(default=False, verbose_name='bookmarked by recipient')),
                ('sender_archived', models.BooleanField(default=False, verbose_name='archived by sender')),
                ('recipient_archived', models.BooleanField(default=False, verbose_name='archived by recipient')),
                ('sender_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted by sender at')),
                ('recipient_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted by recipient at')),
                ('moderation_status', models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('r', 'Rejected')], default='a', max_length=1, verbose_name='status')),
                ('moderation_date', models.DateTimeField(blank=True, null=True, verbose_name='moderated at')),
                ('moderation_reason', models.CharField(blank=True, max_length=120, verbose_name='rejection reason')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postman.Interaction')),
            ],
            options={
                'ordering': ['-sent_at'],
                'verbose_name': 'attachment interaction',
                'verbose_name_plural': 'attachment interactions',
            },
            bases=('postman.interaction',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('interaction_ptr', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postman.Interaction')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('last_emailed_owner', models.DateTimeField(blank=True, null=True)),
                ('last_emailed_bidder', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
            bases=('postman.interaction',),
        ),
        migrations.AddField(
            model_name='interaction',
            name='moderation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_interactions', to=settings.AUTH_USER_MODEL, verbose_name='moderator'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_interaction', to='postman.Interaction', verbose_name='parent interaction'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_interaction', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_interaction', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_interaction', to='postman.Interaction', verbose_name='root interaction'),
        ),
        migrations.CreateModel(
            name='PendingMessage',
            fields=[
            ],
            options={
                'verbose_name': 'pending message',
                'proxy': True,
                'verbose_name_plural': 'pending messages',
            },
            bases=('postman.message',),
        ),
    ]
