# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_job_message'),
        ('postman', '0002_auto_20160217_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Job'),
        ),
        migrations.AddField(
            model_name='message',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Project'),
        ),
    ]
