# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0004_auto_20160608_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
