# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_nda'),
        ('postman', '0005_auto_20160616_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.NDA'),
        ),
    ]
