# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0006_message_nda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at', 'id'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
