# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0007_auto_20160720_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at', '-id'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
