# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0009_auto_20160728_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='document',
            new_name='msa',
        ),
    ]
