# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_auto_20160801_1356'),
        ('postman', '0010_auto_20160801_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Terms'),
        ),
    ]
