# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0011_message_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Document'),
        ),
        migrations.AlterField(
            model_name='message',
            name='nda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nda', to='business.Document'),
        ),
    ]
