# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0013_auto_20160823_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
