# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0014_auto_20160830_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
