# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0015_message_last_emailed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='last_emailed',
            new_name='last_emailed_bidder',
        ),
        migrations.AddField(
            model_name='message',
            name='last_emailed_owner',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
