# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0018_split_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentinteraction',
            name='interaction_ptr',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postman.Interaction'),
        ),
        migrations.AlterField(
            model_name='message',
            name='interaction_ptr',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postman.Interaction'),
        ),
    ]
