# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0019_auto_20160914_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='subject'),
        ),
    ]
