# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-20 03:53
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0020_auto_20161005_1919'),
    ]
