# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0021_add_unread_alerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='job',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msa',
        ),
        migrations.RemoveField(
            model_name='message',
            name='nda',
        ),
        migrations.RemoveField(
            model_name='message',
            name='project',
        ),
        migrations.RemoveField(
            model_name='message',
            name='terms',
        ),
    ]
