# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-04 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set([('submitter', 'project')]),
        ),
    ]
