# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-04 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20170304_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
