# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20171031_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
