# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-08 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('proposals', '0004_auto_20170306_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postman.Message'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('declined', 'Declined')], default=b'pending', max_length=100),
        ),
    ]
