# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20170308_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ('-create_date',)},
        ),
        migrations.AlterField(
            model_name='proposal',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='equity',
            field=models.BooleanField(default=False),
        ),
    ]
