# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_auto_20170410_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
