# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('test_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('coverage', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('passing_marks', models.IntegerField()),
            ],
        ),
    ]
