# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('expertratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='_Tagulous_SkillTest_coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.RemoveField(
            model_name='skilltest',
            name='coverage',
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_skilltest_coverage',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='coverage',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', to='expertratings._Tagulous_SkillTest_coverage'),
        ),
    ]
