# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expertratings', '0002_auto_20160713_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTestResult',
            fields=[
                ('transcript_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('percentage', models.IntegerField()),
                ('percentile', models.IntegerField()),
                ('average_score', models.IntegerField()),
                ('test_result', models.CharField(choices=[(b'PASS', b'PASS'), (b'FAIL', b'FAIL')], max_length=10)),
                ('time', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertratings.SkillTest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTestUserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_rating', models.IntegerField()),
                ('content_comments', models.CharField(max_length=500)),
                ('procedure_rating', models.IntegerField()),
                ('procedure_comments', models.CharField(max_length=500)),
                ('errors_found', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO')], max_length=10)),
                ('errors_details', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertratings.SkillTestResult')),
            ],
        ),
    ]
