# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertratings', '0003_skilltestresult_skilltestuserfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltestresult',
            name='average_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='skilltestresult',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
