# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-31 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertratings', '0005_auto_20160714_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltest',
            name='sync_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 31, 12, 36, 24, 14802)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilltest',
            name='sync_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='sync_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 31, 12, 36, 36, 747908)),
            preserve_default=False,
        ),
    ]
