# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expertratings', '0006_auto_20160831_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltestuserfeedback',
            name='test_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expertratings.SkillTestResult'),
        ),
    ]
