# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-12 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20171012_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('legal_entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('ein', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'EIN')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'provider/logo')),
                ('description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('llc', 'Limited Liability Company (LLC)'), ('inc', 'Corporation (Inc)'), ('sp', 'Sole Proprietorship'), ('lp', 'Limited Partnership'), ('llp', 'Limited Liability Partnership'), ('nonprofit', 'Non-Profit')], max_length=100, null=True)),
                ('filing_location', models.CharField(blank=True, max_length=100, null=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-current', '-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default=b'new', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255)),
                ('type', models.CharField(choices=[('art', 'Art and Design'), ('technology', 'Technology'), ('gaming', 'Gaming'), ('nonprofit', 'Non-Profit'), ('social', 'Social'), ('news', 'News and Publishing'), ('music', 'Music and Media'), ('location', 'Location-Based'), ('health', 'Health and Fitness')], max_length=100, null=True, blank=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('estimated_hours', models.IntegerField(blank=True, null=True)),
                ('estimated_cash', models.IntegerField(blank=True, null=True)),
                ('estimated_equity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estimated_equity_shares', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('remote', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('mix', models.BooleanField(default=False)),
                ('background', models.TextField(blank=True, null=True)),
                ('progress', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('specs', models.TextField(blank=True, null=True)),
                ('private_info', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('years', models.IntegerField(blank=True, null=True)),
                ('employment_type', models.CharField(default=b'freelance', max_length=100)),
                ('autorenew', models.BooleanField(default=False)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Company')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', blank=True, help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', null=True, to='accounts.Skills')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
