# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-01 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20171012_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
