# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_project_featured_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'project'),
        ),
    ]
