# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_tagline',
            new_name='short_blurb',
        ),
    ]
