# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20160419_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(default=b'PENDING', max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Project')),
            ],
        ),
    ]
