# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('art', 'Art and Design'), ('technology', 'Technology'), ('gaming', 'Gaming'), ('nonprofit', 'Non-Profit'), ('social', 'Social'), ('news', 'News and Publishing'), ('music', 'Music and Media'), ('location', 'Location-Based'), ('health', 'Health and Fitness')], default='technology', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('1', 'Non-Disclosure Agreement'), ('2', 'Contract Service Agreement'), ('3', 'Non-Compete Agreement')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], max_length=100, null=True),
        ),
    ]
