# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20160427_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='message',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('signed', 'Signed')], default=b'sent', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Non-Disclosure', 'Non-Disclosure Agreement'), ('Contract Service', 'Contract Service Agreement'), ('Non-Compete', 'Non-Compete Agreement')], max_length=100),
        ),
    ]
