# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20160428_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='message',
        ),
    ]
