# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 08:51
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_job_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='_Tagulous_Project_skills',
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', to='accounts.Skills'),
        ),
    ]
