# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20160505_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='_Tagulous_Project_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='_Tagulous_Project_secondary_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', blank=True, initial='Angular.js, JQuery, Python, nginx, uwsgi', null=True, on_delete=django.db.models.deletion.CASCADE, to='business._Tagulous_Company_category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', blank=True, initial='Angular.js, JQuery, Python, nginx, uwsgi', null=True, on_delete=django.db.models.deletion.CASCADE, to='business._Tagulous_Project_category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_project_secondary_category',
            unique_together=set([('slug',)]),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_project_location',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', blank=True, initial='Angular.js, JQuery, Python, nginx, uwsgi', null=True, on_delete=django.db.models.deletion.CASCADE, to='business._Tagulous_Project_location'),
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_category',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', blank=True, initial='Angular.js, JQuery, Python, nginx, uwsgi', null=True, on_delete=django.db.models.deletion.CASCADE, to='business._Tagulous_Project_secondary_category'),
        ),
    ]
