# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20160505_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template_id',
            field=models.CharField(default=None, max_length=100, blank=True, null=True),
            preserve_default=False,
        ),
    ]
