# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_document_template_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Non-Disclosure', 'Non-Disclosure Agreement'), ('Contract Service', 'Contract Service Agreement'), ('Non-Compete', 'Non-Compete Agreement')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplateRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.DocumentTemplate')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='business.DocumentTemplate'),
            preserve_default=False,
        ),
    ]
