# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docusign', '__first__'),
        ('business', '0013_auto_20160606_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='documenttemplaterole',
            name='template',
        ),
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docusign.DocumentTemplate', null=True),
        ),
        migrations.DeleteModel(
            name='DocumentTemplate',
        ),
        migrations.DeleteModel(
            name='DocumentTemplateRole',
        ),
        migrations.AddField(
            model_name='documentsigner',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Document'),
        ),
        migrations.AddField(
            model_name='documentsigner',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsigner',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docusign.DocumentTemplateRole'),
        ),
    ]
