# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20160607_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsigner',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentsigner',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='documentsigner',
            name='role',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='template',
        ),
    ]
