# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20160607_0308'),
        ('docusign', '0004_auto_20160607_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docusign_document',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='docusign.Document', null=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocumentSigner',
        ),
    ]
