# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20160607_0308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentSigner',
        ),
    ]
