# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 13:29
from __future__ import unicode_literals

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20160607_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bid_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=business.models.business_attachments),
        ),
    ]
