# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20160616_1329'),
        ('business', '0018_confidentialinfo'),
    ]

    operations = [
    ]
