# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentialinfo',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
