# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_auto_20160629_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='_Tagulous_Project_category',
        ),
        migrations.DeleteModel(
            name='_Tagulous_Project_location',
        ),
        migrations.DeleteModel(
            name='_Tagulous_Project_secondary_category',
        ),
    ]
