# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 03:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0024_auto_20160630_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='primary_contact',
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('llc', 'Limited Liability Company (LLC)'), ('inc', 'Corporation (Inc)'), ('sp', 'Sole Proprietorship'), ('lp', 'Limited Partnership'), ('llp', 'Limited Liability Partnership'), ('nonprofit', 'Non-Profit')], default='llc', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
