# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_auto_20160713_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='nda_signed',
            field=models.BooleanField(default=False),
        ),
    ]
