# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion

def break_out_details(apps, schema_editor):
    Project = apps.get_model("business", "Project")
    Info = apps.get_model("business", "ProjectInfo")
    for project in Project.objects.all():
        info = Info(project=project, description=project.description, type='primary', title='Project Overview')
        info.save()
        project.details = info
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_auto_20160717_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'public', b'Publicly Visible'), (b'private', b'Only visible to Project Participants')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='confidentialinfo',
            name='project',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='_project', serialize=False, to='business.ProjectInfo', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(break_out_details),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='_project', serialize=False, to='business.ProjectInfo'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimated_equity',
        ),
       #migrations.RemoveField(
       #    model_name='project',
       #    name='id',
       #),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 11, 18, 34, 421969)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_equity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_equity_shares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 11, 18, 46, 751844)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ConfidentialInfo',
        ),
    ]
