# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_break_out_details_20160721_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', null=True, to='business.Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_project', to='business.ProjectInfo'),
        ),
    ]
