# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20160721_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='details',
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='type',
            field=models.CharField(choices=[(b'primary', b'Project Overview'), (b'public', b'Publicly Visible'), (b'private', b'Only visible to Project Participants')], max_length=100),
        ),
    ]
