# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_auto_20160722_0001'),
        ('business', '0028_nda'),
    ]

    operations = [
    ]
