# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-28 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0009_auto_20160728_1147'),
        ('business', '0031_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nda',
            name='project',
        ),
        migrations.RemoveField(
            model_name='nda',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='bid_message',
        ),
        migrations.AlterField(
            model_name='document',
            name='docusign_document',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='docusign.Document'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('art', 'Art and Design'), ('technology', 'Technology'), ('gaming', 'Gaming'), ('nonprofit', 'Non-Profit'), ('social', 'Social'), ('news', 'News and Publishing'), ('music', 'Music and Media'), ('location', 'Location-Based'), ('health', 'Health and Fitness')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='NDA',
        ),
    ]
