# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_auto_20160728_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('milestones', models.TextField(blank=True, null=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('halfway', models.CharField(blank=True, max_length=255, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Job')),
            ],
        ),
    ]
