# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='equity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
