# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_auto_20160729_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='contractee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terms',
            name='contractor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='schedule',
            field=models.CharField(blank=True, choices=[('50% upfront and 50% upon completion', '50% upfront and 50% upon completion'), ('50% at a halfway milestone and 50% upon completion', '50% at a halfway milestone and 50% upon completion')], max_length=255, null=True),
        ),
    ]
