# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20160730_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('in progress', 'In Progress'), ('preview', 'Preview')], default=6, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', blank=True, help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', to='business.Category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('NDA', 'Non-Disclosure Agreement'), ('MSA', 'Contract Service Agreement'), ('NC', 'Non-Compete Agreement')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=b'skills_autocomplete', help_text='Enter a comma-separated tag string', initial='Angular.js, JQuery, Python, nginx, uwsgi', to='business.Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='terms',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terms',
            name='contractee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terms',
            name='contractor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terms',
            name='end_date',
            field=models.DateField(default='2016-10-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terms',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terms',
            name='start_date',
            field=models.DateField(default='2016-10-10'),
            preserve_default=False,
        ),
    ]
