# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_auto_20160801_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='status',
            field=models.CharField(default=b'new', max_length=100),
        ),
    ]
