# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_auto_20160801_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default=b'new', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='docusign_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docusign.Document'),
        ),
    ]
