# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_auto_20160802_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='developer',
            new_name='contractor',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.Project'),
            preserve_default=False,
        ),
    ]
