# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_auto_20160802_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
    ]
