# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_auto_20160802_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='create_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 4, 9, 35, 55, 929738, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terms',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
    ]
