# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-07 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_remove_document_project'),
        ('business', '0042_auto_20160804_0935'),
    ]

    operations = [
    ]
