# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_auto_20160809_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
    ]
