# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_remove_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
