# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0045_project_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default=b'new', max_length=100),
        ),
    ]
