# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_auto_20160810_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='a'),
            preserve_default=False,
        ),
    ]
