# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_auto_20160810_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
    ]
