# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0051_auto_20160815_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_cash',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
