# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0052_auto_20160816_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='equity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Job'),
        ),
    ]
