# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0053_auto_20160818_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='schedule',
            field=models.CharField(blank=True, choices=[('50% upfront and 50% upon completion', '50% upfront and 50% upon completion'), ('50% at a halfway milestone and 50% upon completion', '50% at a halfway milestone and 50% upon completion')], default=b'50% upfront and 50% upon completion', max_length=255, null=True),
        ),
    ]
