# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0054_auto_20160823_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='milestones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='private_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='specs',
            field=models.TextField(blank=True),
        ),
    ]
