# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0056_auto_20160914_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'project-images'),
        ),
    ]
