# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0057_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
