# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0061_project_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='filing_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True, choices=[('llc', 'Limited Liability Company (LLC)'), ('inc', 'Corporation (Inc)'), ('sp', 'Sole Proprietorship'), ('lp', 'Limited Partnership'), ('llp', 'Limited Liability Partnership'), ('nonprofit', 'Non-Profit')], max_length=100, null=True),
        ),
    ]
