# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-30 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0062_auto_20161109_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-current', '-end_date', '-start_date']},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('connected', 'Connected'), ('active', 'Active'), ('completed', 'Completed')], default=b'pending', max_length=100, null=True),
        ),
    ]
