# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-01 19:14
from __future__ import unicode_literals
from django.db import migrations, models


def size(title):
    return len(title or "")

def move_title(apps, schema_editor):
    Employee = apps.get_model('business', 'Employee')
    for employee in Employee.objects.all():
        profile = employee.profile
        if(size(profile.title) > size(employee.title)):
            employee.title = profile.title
            employee.save()
        profile.title = None
        profile.save()


def reverse_title(apps, schema_editor):
    " for reversing the migration "
    Employee = apps.get_model('business', 'Employee')
    for employee in Employee.objects.all():
        profile = employee.profile
        if(size(employee.title) > size(profile.title)):
            profile.title = employee.title
            profile.save()
        employee.title = None
        employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0063_auto_20161130_0016'),
    ]

    operations = [
        migrations.RunPython(move_title, reverse_code=reverse_title),
    ]
