# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0064_employee_titles_20161201_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='terms',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
