# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0065_auto_20161226_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='incorporation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ein',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'EIN'),
        ),
    ]
