# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 21:40
from __future__ import unicode_literals

from django.db import migrations, models

def delete_project_images(apps, schema_editor):
    Project = apps.get_model('business', 'Project')
    for project in Project.objects.filter(project_image__isnull=False):
        project.project_image.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0066_auto_20170202_1651'),
    ]

    operations = [
        migrations.RunPython(delete_project_images),
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
    ]
