# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-28 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0067_auto_20170223_0752'),
        ('business', '0067_remove_project_images'),
    ]

    operations = [
    ]
