# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0070_nda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='zipcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
