# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0022_auto_20170802_2124'),
        ('reviews', '0006_auto_20170802_2124'),
        ('business', '0071_auto_20170410_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='job',
            name='project',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='job',
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='employment_type',
            field=models.CharField(default=b'freelance', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Terms',
        ),
    ]
