# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-25 18:29
from __future__ import unicode_literals

from django.db import migrations

def remap_project_fields(apps, schema_editor):
    Project = apps.get_model('business', 'Project')
    for project in Project.objects.filter(approved=True, published=True):
        project.background = '{0}\n\nWhere we are today\n{1}\n\nDeliverables and specs\n{2}\n\nMilestones\n{3}'.format(project.background, project.progress, project.specs, project.milestones)
        project.specs = project.scope
        project.scope = project.short_blurb
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('business', '0075_auto_20170822_1850'),
    ]

    operations = [
        migrations.RunPython(remap_project_fields),
        migrations.RemoveField(
            model_name='project',
            name='milestones',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_blurb',
        ),
        migrations.RemoveField(
            model_name='project',
            name='video_url',
        ),
    ]
