# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-08 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0076_auto_20170825_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autorenew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
