# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-08 01:18
from __future__ import unicode_literals
from datetime import datetime, timedelta

from django.db import migrations, models


def add_expiry_dates(apps, schema_editor):
    Project = apps.get_model('business', 'Project')
    for project in Project.objects.filter(approved=True, published=True):
        today = datetime.now().date()
        project.expire_date = today + timedelta(days=30)
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('business', '0076_auto_20170825_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autorenew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(add_expiry_dates),
    ]
