# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0077_auto_20170908_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
