
DISCIPLINES = {
    'design': 'Design',
    'development': 'Mobile/Web/App Development',
    'marketing': 'Marketing',
    'copy-content': 'Copy & Content',
    'strategy-research': 'Strategy & Research',
    'product-management': 'Product Management',
    'video-photo': 'Video & Photo',
    'project-management': 'Project Management'
}

ROLES = {
    'design': {
        'graphic-designer': 'Graphic Designer',
        'logo-designer': 'Logo/Brand Designer',
        'product-designer': 'Product Designer',
        'industrial-designer': 'Industrial Designer',
        'illustrator': 'Illustrator',
        'animator': 'Animator',
        'ux-ui-designer': 'UX/UI Designer',
        'motion-designer': 'Motion Designer',
        'presentation-designer': 'Presentation Designer',
        'packaging-designer': 'Packaging Designer',
        'print-designer': 'Print Designer',
        'web-designer': 'Web Designer',
    },
    'development': {
        'full-stack': 'Full-stack Developer',
        'front-end': 'Front-end Developer',
        'back-end': 'Back-end Developer',
        'mobile': 'Mobile Developer',
        'ios': 'iOS Developer',
        'android': 'Android Developer',
        'game': 'Game Developer',
        'software': 'Software Developer',
        'devops': 'DevOps Engineer',
        'database': 'Database Engineer',
        'qa': 'QA Engineer',
    },
    'marketing': {
        'marketing-strategist': 'Marketing Strategist',
        'marketing-consultant': 'Marketing Consultant',
        'social-media-marketing-strategist': 'Social Media Marketing Strategist',
        'social-media-copywriter': 'Social Media Copywriter',
        'seo-specialist': 'SEO Specialist',
        'seo-strategist': 'SEO Strategist',
    },
    'copy-content': {
        'creative-copywriter': 'Creative Copywriter',
        'marketing-copywriter': 'Marketing Copywriter',
        'content-copywriter': 'Content Copywriter',
        'digital-marketing-copywriter': 'Digital Marketing Copywriter',
        'digital-content-writer': 'Digital Content Writer',
        'social-media-copywriter': 'Social Media Copywriter',
        'content-strategist': 'Content Strategist',
        'content-editor': 'Content Editor',
        'blog-writer': 'Blog Writer',
        'article-writer': 'Article Writer',
        'copy-editor': 'Copy Editor',
        'proofreader': 'Proofreader',
    },
    'strategy-research': {
        'market-researcher': 'Market Researcher',
        'user-researcher': 'User Researcher',
        'strategy-consultant': 'Strategy Consultant',
        'analytics-specialist': 'Analytics Specialist',
    },
    'product-management': {
        'product-strategist': 'Product Strategist',
        'product-manager': 'Product Manager',
        'business-strategist': 'Business Strategist',
        'public-relations-specialist': 'Public Relations Specialist',
    },
    'video-photo': {
        'videographer': 'Videographer',
        'photographer': 'Photographer',
        'video-editor': 'Video Editor',
        'photo-editor': 'Photo Editor',
        'special-effects-engineer': 'Special Effects Engineer',
        'video-producer': 'Video Producer',
        'post-production-specialist': 'Post Production Specialist',
    },
    'project-management': {
        'project-manager': 'Project Manager',
    }
}
