# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20160804_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_charged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
