# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-09 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def payer_to_requester(apps, schema_editor):
    Order = apps.get_model('payment', 'ProductOrder')
    for order in Order.objects.all():
        order.requester = order.payer
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_auto_20161130_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='status',
            new_name='_status',
        ),
        migrations.AddField(
            model_name='productorder',
            name='_product_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(payer_to_requester),
        migrations.AlterField(
            model_name='productorder',
            name='requester',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
