# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-09 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20161209_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='_product_status',
            new_name='request_status',
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='_status',
            new_name='status',
        ),
    ]
