# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-30 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20161209_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='promo',
            new_name='_promo',
        ),
    ]
