# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-28 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20161230_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='result',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
