# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models

from payment.helpers import stripe_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20170328_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='brand',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='last4',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
