# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20170614_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='recipient_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
