# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-20 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20170615_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
