# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_invoice_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
