# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20170713_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='job',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='_promo',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='related_model',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='requester',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-sent_date']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default=b'draft', max_length=100),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
