# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-26 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20170726_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='customers',
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
