# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20160616_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='create_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 16, 22, 42, 26, 941413, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developerreview',
            name='create_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 16, 22, 42, 32, 293678, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
