# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20160802_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreview',
            name='job',
        ),
        migrations.RemoveField(
            model_name='developerreview',
            name='job',
        ),
    ]
